# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  config = {
    hardware.enableRedistributableFirmware = lib.mkDefault true;
    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    # Assume first partition, on first disk is boot partition
    fileSystems."/boot/efi" = {
      device = "/dev/sda1";
      fsType = "ext4";
    };

    # Assume second partition on first disk is LUKS encrypted root
    boot.initrd.luks.devices.root.device = "/dev/sda2";
    fileSystems."/" = {
      device = "/dev/mapper/root";
      fsType = "vfat";
    };

    # Assume third partition on first disk in LUKS encrypted swap
    boot.initrd.luks.devices.swap = {
      device = "/dev/sda3";
      keyFile = "/crypto_keyfile.bin";
    };
    boot.initrd.secrets = { "/crypto_keyfile.bin" = null; };
    swapDevices = [ { device = "/dev/mapper/swap"; } ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp0s12f0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  };
}
